[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"

# Community #

[kmon]
source = "github"
github = "orhun/kmon"
use_latest_release = true
prefix = "v"

[menyoki]
source = "github"
github = "orhun/menyoki"
use_latest_release = true
prefix = "v"

[lychee-link-checker]
source = "github"
github = "lycheeverse/lychee"
use_latest_release = true
prefix = "v"

[cargo-tarpaulin]
source = "github"
github = "xd009642/tarpaulin"
use_max_tag = true
prefix = "v"

[cargo-spellcheck]
source = "github"
github = "drahnr/cargo-spellcheck"
use_latest_release = true
prefix = "v"

[cargo-outdated]
source = "github"
github = "kbknapp/cargo-outdated"
use_latest_tag = true
prefix = "v"

[cargo-edit]
source = "github"
github = "killercup/cargo-edit"
use_latest_release = true
prefix = "v"

[cargo-bloat]
source = "github"
github = "RazrFalcon/cargo-bloat"
use_max_tag = true
prefix = "v"

[cargo-udeps]
source = "github"
github = "est31/cargo-udeps"
use_latest_release = true
prefix = "v"

[cargo-depgraph]
source = "regex"
url = "https://git.sr.ht/~jplatte/cargo-depgraph"
regex = "<dt>v(.*)</dt>"

[onefetch]
source = "github"
github = "o2sh/onefetch"
use_latest_release = true
prefix = "v"

[viu]
source = "github"
github = "atanunq/viu"
use_latest_release = true
prefix = "v"

[xdo]
source = "github"
github = "baskerville/xdo"
use_max_tag = true
prefix = "v"

[mdbook]
source = "github"
github = "rust-lang/mdBook"
use_latest_release = true
prefix = "v"

[ali]
source = "github"
github = "nakabonne/ali"
use_latest_release = true
prefix = "v"

[gping]
source = "github"
github = "orf/gping"
use_latest_release = true
prefix = "v"

[dog]
source = "github"
github = "ogham/dog"
use_latest_release = true
prefix = "v"

[dumb]
source = "github"
github = "kode54/dumb"
use_max_tag = true
prefix = "v"

[zps]
source = "github"
github = "orhun/zps"
use_latest_release = true
prefix = "v"

[shy]
source = "github"
github = "xvxx/shy"
use_max_tag = true
prefix = "v"

[mari0]
source = "github"
github = "Stabyourself/mari0"
use_latest_release = true
prefix = "v"

[mdp]
source = "github"
github = "visit1985/mdp"
use_max_tag = true
prefix = "v"

[racer]
source = "github"
github = "racer-rust/racer"
use_latest_release = true
prefix = "v"

[tokei]
source = "github"
github = "XAMPPRocky/tokei"
use_latest_release = true
prefix = "v"

[hex]
source = "github"
github = "sitkevij/hex"
use_latest_release = true
prefix = "v"

[lsd]
source = "github"
github = "Peltoche/lsd"
use_latest_release = true
prefix = "v"

[hexyl]
source = "github"
github = "sharkdp/hexyl"
use_latest_release = true
prefix = "v"

[scrot]
source = "github"
github = "resurrecting-open-source-projects/scrot"
use_latest_release = true
prefix = "v"

[procs]
source = "github"
github = "dalance/procs"
use_latest_release = true
prefix = "v"

[task]
source = "github"
github = "GothenburgBitFactory/taskwarrior"
use_latest_release = true
prefix = "v"

[taskwarrior-tui]
source = "github"
github = "kdheepak/taskwarrior-tui"
use_latest_release = true
prefix = "v"

[lnav]
source = "github"
github = "tstack/lnav"
use_latest_release = true
prefix = "v"

[xh]
source = "github"
github = "ducaale/xh"
use_latest_release = true
prefix = "v"

[pueue]
source = "github"
github = "nukesor/pueue"
use_latest_release = true
prefix = "v"

[aws-vault]
source = "github"
github = "99designs/aws-vault"
use_latest_release = true
prefix = "v"

[alicloud-vault]
source = "github"
github = "arafato/alicloud-vault"
use_latest_release = true
prefix = "v"

[aliyun-cli]
source = "github"
github = "aliyun/aliyun-cli"
use_latest_release = true
prefix = "v"

[wezterm]
source = "github"
github = "wez/wezterm"
use_latest_release = true
prefix = "v"

[tickrs]
source = "github"
github = "tarkah/tickrs"
use_latest_release = true
prefix = "v"

[uutils-coreutils]
source = "github"
github = "uutils/coreutils"
use_latest_release = true
prefix = "v"

[innernet]
source = "github"
github = "tonarino/innernet"
use_latest_release = true
prefix = "v"

[xplr]
source = "github"
github = "sayanarijit/xplr"
use_latest_release = true
prefix = "v"

[lucky-commit]
source = "github"
github = "not-an-aardvark/lucky-commit"
use_max_tag = true
prefix = "v"

[lfs]
source = "github"
github = "Canop/lfs"
use_latest_release = true
prefix = "v"

[rhit]
source = "github"
github = "Canop/rhit"
use_latest_release = true
prefix = "v"

[cargo-expand]
source = "github"
github = "dtolnay/cargo-expand"
use_latest_release = true
prefix = "v"

[helix]
source = "github"
github = "helix-editor/helix"
use_latest_release = true
prefix = "v"

[rpg-cli]
source = "github"
github = "facundoolano/rpg-cli"
use_latest_release = true
prefix = "v"

[cargo-generate]
source = "github"
github = "cargo-generate/cargo-generate"
use_latest_release = true
prefix = "v"

[songrec]
source = "github"
github = "marin-m/SongRec"
use_latest_release = true
prefix = "v"

[git-absorb]
source = "github"
github = "tummychow/git-absorb"
use_latest_release = true
prefix = "v"

[binocle]
source = "github"
github = "sharkdp/binocle"
use_latest_release = true
prefix = "v"

[grex]
source = "github"
github = "pemistahl/grex"
use_latest_release = true
prefix = "v"

[atuin]
source = "github"
github = "ellie/atuin"
use_latest_release = true
prefix = "v"

[kubie]
source = "github"
github = "sbstp/kubie"
use_latest_release = true
prefix = "v"

[fishfight]
source = "github"
github = "fishfight/FishFight"
use_latest_release = true
prefix = "v"

[mcfly]
source = "github"
github = "cantino/mcfly"
use_latest_release = true
prefix = "v"

[fq]
source = "github"
github = "wader/fq"
use_latest_release = true
prefix = "v"

[rathole]
source = "github"
github = "rapiz1/rathole"
use_latest_release = true
prefix = "v"

[gfold]
source = "github"
github = "nickgerace/gfold"
use_max_tag = true
prefix = "v"

[gifski]
source = "github"
github = "ImageOptim/gifski"
use_latest_release = true
prefix = "v"

[wasm-pack]
source = "github"
github = "rustwasm/wasm-pack"
use_latest_release = true
prefix = "v"

[cocogitto]
source = "github"
github = "oknozor/cocogitto"
use_latest_release = true
prefix = "v"

[gsmartcontrol]
source = "github"
github = "ashaduri/gsmartcontrol"
use_latest_release = true
prefix = "v"

[broot]
source = "github"
github = "Canop/broot"
use_latest_release = true
prefix = "v"

[rnote]
source = "github"
github = "flxzt/rnote"
use_latest_release = true
prefix = "v"

[himalaya]
source = "github"
github = "soywod/himalaya"
use_latest_release = true
prefix = "v"

[cargo-msrv]
source = "github"
github = "foresterre/cargo-msrv"
use_latest_release = true
prefix = "v"

[rustup]
source = "github"
github = "rust-lang/rustup"
use_max_tag = true
prefix = "v"

[intellij-idea-community-edition]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='IntelliJ IDEA']/channel[@status='release']/build/@fullNumber)\" -"

[pycharm-community-edition]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='PyCharm']/channel[@status='release']/build/@fullNumber)\" -"

[kooha]
source = "github"
github = "SeaDve/Kooha"
use_latest_release = true
prefix = "v"

# AUR #

[kermit]
source = "github"
github = "orhun/kermit"
use_latest_release = true
prefix = "v"

[pkgtop]
source = "github"
github = "orhun/pkgtop"
use_latest_release = true
prefix = "v"

[god]
source = "github"
github = "orhun/god"
use_latest_release = true
prefix = "v"

[i3-workspace-brightness]
source = "github"
github = "orhun/i3-workspace-brightness"
use_latest_release = true
prefix = "v"

[notp]
source = "github"
github = "kondanta/notp"
use_latest_release = true
prefix = "v"

[jilu]
source = "github"
github = "rustic-games/jilu"
use_latest_release = true
prefix = "v"

[hadlock]
source = "github"
github = "AdaShoelace/hadlock"
use_latest_release = true
prefix = "v"

[mmwm]
source = "github"
github = "kaugm/mmwm"

[frankenwm]
source = "github"
github = "sulami/FrankenWM"
use_max_tag = true
prefix = "v"

[conserve]
source = "github"
github = "sourcefrog/conserve"
use_latest_release = true
prefix = "v"

[stegano]
source = "github"
github = "steganogram/stegano-rs"
use_max_tag = true
prefix = "v"

[stegify]
source = "github"
github = "DimitarPetrov/stegify"
use_latest_release = true
prefix = "v"

[kbtui]
source = "github"
github = "Rudi9719/kbtui"
use_latest_release = true
prefix = "v"

[lipl]
source = "github"
github = "yxdunc/lipl"
use_latest_release = true
prefix = "v"

[kbs2]
source = "github"
github = "woodruffw/kbs2"
use_latest_release = true
prefix = "v"

[suckit]
source = "github"
github = "Skallwar/suckit"
use_latest_release = true
prefix = "v"

[funkicrab]
source = "github"
github = "zesterer/funkicrab"

[fhc]
source = "github"
github = "Edu4rdSHL/fhc"
use_latest_release = true
prefix = "v"

[eva]
source = "github"
github = "NerdyPepper/eva"
use_latest_release = true
prefix = "v"

[rusolver]
source = "github"
github = "Edu4rdSHL/rusolver"
use_latest_release = true
prefix = "v"

[unimap]
source = "github"
github = "Edu4rdSHL/unimap"
use_latest_release = true
prefix = "v"

[rusty-krab-manager]
source = "github"
github = "aryakaul/rusty-krab-manager"
use_latest_release = true
prefix = "v"

[huniq]
source = "github"
github = "koraa/huniq"

[slicer]
source = "github"
github = "mzfr/slicer"
use_latest_release = true
prefix = "v"

[pwninit]
source = "github"
github = "io12/pwninit"
use_latest_release = true
prefix = "v"

[typeracer]
source = "gitlab"
gitlab = "ttyperacer/terminal-typeracer"
use_max_tag = true
prefix = "v"

[termimage]
source = "github"
github = "nabijaczleweli/termimage"
use_latest_release = true
prefix = "v"

[imgcat]
source = "github"
github = "trashhalo/imgcat"
use_latest_release = true
prefix = "v"

[muffet]
source = "github"
github = "raviqqe/muffet"
use_latest_release = true
prefix = "v"

[termchat]
source = "github"
github = "lemunozm/termchat"
use_latest_release = true
prefix = "v"

[fw]
source = "github"
github = "brocode/fw"
use_latest_release = true
prefix = "v"

[fblog]
source = "github"
github = "brocode/fblog"
use_latest_release = true
prefix = "v"

[goat]
source = "github"
github = "brocode/goat"
use_latest_release = true
prefix = "v"

[sic-image-cli]
source = "github"
github = "foresterre/sic"
use_latest_release = true
prefix = "v"

[globe]
source = "github"
github = "adamsky/globe"
use_max_tag = true
prefix = "v"

[cicero]
source = "github"
github = "eyeplum/cicero-tui"
use_latest_release = true
prefix = "v"

[verco]
source = "github"
github = "matheuslessarodrigues/verco"
use_latest_release = true
prefix = "v"

[color_blinder]
source = "gitlab"
gitlab = "dns2utf8/color_blinder"
use_max_tag = true
prefix = "v"

[bookmark]
source = "github"
github = "Szymongib/bookmark"
use_latest_release = true
prefix = "v"

[emptty]
source = "github"
github = "tvrzna/emptty"
use_latest_release = true
prefix = "v"

[fclones]
source = "github"
github = "pkolaczk/fclones"
use_latest_release = true
prefix = "v"

[dotter-rs]
source = "github"
github = "SuperCuber/dotter"
use_latest_release = true
prefix = "v"

[ctree]
source = "github"
github = "Matt-Gleich/ctree"
use_latest_release = true
prefix = "v"

#[prs]
#source = "gitlab"
#gitlab = "timvisee/prs"
#use_max_tag = true
#prefix = "v"

[t-rec]
source = "github"
github = "sassman/t-rec-rs"
use_latest_release = true
prefix = "v"

[rdfm]
source = "github"
github = "Wafelack/rdfm"
use_max_tag = true
prefix = "v"

[cns]
source = "github"
github = "adamsky/cns"
use_max_tag = true
prefix = "v"

[tz]
source = "github"
github = "oz/tz"
use_latest_release = true
prefix = "v"

[miro]
source = "github"
github = "o2sh/miro"
use_latest_release = true
prefix = "v"

[termusic]
source = "github"
github = "tramhao/termusic"
use_max_tag = true
prefix = "v"

[zellij]
source = "github"
github = "zellij-org/zellij"
use_latest_release = true
prefix = "v"

[cargo-about]
source = "github"
github = "EmbarkStudios/cargo-about"
use_latest_release = true
prefix = "v"

[cargo-binstall]
source = "github"
github = "ryankurte/cargo-binstall"
use_latest_release = true
prefix = "v"

[cargo-sonar]
source = "gitlab"
gitlab = "woshilapin/cargo-sonar"
use_max_tag = true
prefix = "v"

[arti]
source = "gitlab"
host = "gitlab.torproject.org"
gitlab = "tpo/core/arti"
use_max_tag = true
prefix = "arti-v"

[dra]
source = "github"
github = "devmatteini/dra"
use_latest_release = true
prefix = "v"

[toml2json]
source = "github"
github = "woodruffw/toml2json"
use_latest_release = true
prefix = "v"

[rustfilt]
source = "github"
github = "luser/rustfilt"
use_latest_release = true
prefix = "v"
