[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"

# Community #

[kmon]
source = "github"
github = "orhun/kmon"
use_latest_release = true
prefix = "v"

[menyoki]
source = "github"
github = "orhun/menyoki"
use_latest_release = true
prefix = "v"

[lychee-rs]
source = "github"
github = "lycheeverse/lychee"
use_latest_release = true
prefix = "v"

[cargo-tarpaulin]
source = "github"
github = "xd009642/tarpaulin"
use_max_tag = true
prefix = "v"

[cargo-spellcheck]
source = "github"
github = "drahnr/cargo-spellcheck"
use_latest_release = true
prefix = "v"

[cargo-outdated]
source = "github"
github = "kbknapp/cargo-outdated"
use_latest_tag = true
prefix = "v"

[cargo-edit]
source = "github"
github = "killercup/cargo-edit"
use_latest_release = true
prefix = "v"

[cargo-bloat]
source = "github"
github = "RazrFalcon/cargo-bloat"
use_max_tag = true
prefix = "v"

[cargo-udeps]
source = "github"
github = "est31/cargo-udeps"
use_latest_release = true
prefix = "v"

[cargo-depgraph]
source = "regex"
url = "https://git.sr.ht/~jplatte/cargo-depgraph"
regex = "<dt>v(.*)</dt>"

[onefetch]
source = "github"
github = "o2sh/onefetch"
use_latest_release = true
prefix = "v"

[viu]
source = "github"
github = "atanunq/viu"
use_latest_release = true
prefix = "v"

[xdo]
source = "github"
github = "baskerville/xdo"
use_max_tag = true
prefix = "v"

[mdbook]
source = "github"
github = "rust-lang/mdBook"
use_latest_release = true
prefix = "v"

[ali]
source = "github"
github = "nakabonne/ali"
use_latest_release = true
prefix = "v"

[gping]
source = "github"
github = "orf/gping"
use_latest_release = true
prefix = "v"

[dog]
source = "github"
github = "ogham/dog"
use_latest_release = true
prefix = "v"

[dumb]
source = "github"
github = "kode54/dumb"
use_max_tag = true
prefix = "v"

[zps]
source = "github"
github = "orhun/zps"
use_latest_release = true
prefix = "v"

[shy]
source = "github"
github = "xvxx/shy"
use_max_tag = true
prefix = "v"

[mari0]
source = "github"
github = "Stabyourself/mari0"
use_latest_release = true
prefix = "v"

[mdp]
source = "github"
github = "visit1985/mdp"
use_max_tag = true
prefix = "v"

[racer]
source = "github"
github = "racer-rust/racer"
use_latest_release = true
prefix = "v"

[tokei]
source = "github"
github = "XAMPPRocky/tokei"
use_latest_release = true
prefix = "v"

[hex]
source = "github"
github = "sitkevij/hex"
use_latest_release = true
prefix = "v"

[lsd]
source = "github"
github = "Peltoche/lsd"
use_latest_release = true
prefix = "v"

[hexyl]
source = "github"
github = "sharkdp/hexyl"
use_latest_release = true
prefix = "v"

[scrot]
source = "github"
github = "resurrecting-open-source-projects/scrot"
use_latest_release = true
prefix = "v"

[procs]
source = "github"
github = "dalance/procs"
use_latest_release = true
prefix = "v"

[task]
source = "github"
github = "GothenburgBitFactory/taskwarrior"
use_latest_release = true
prefix = "v"

[taskwarrior-tui]
source = "github"
github = "kdheepak/taskwarrior-tui"
use_latest_release = true
prefix = "v"

[lnav]
source = "github"
github = "tstack/lnav"
use_latest_release = true
prefix = "v"

[xh]
source = "github"
github = "ducaale/xh"
use_latest_release = true
prefix = "v"

# AUR #

[kermit]
source = "github"
github = "orhun/kermit"
use_latest_release = true
prefix = "v"

[pkgtop]
source = "github"
github = "orhun/pkgtop"
use_latest_release = true
prefix = "v"

[god]
source = "github"
github = "orhun/god"
use_latest_release = true
prefix = "v"

[i3-workspace-brightness]
source = "github"
github = "orhun/i3-workspace-brightness"
use_latest_release = true
prefix = "v"

[notp]
source = "github"
github = "kondanta/notp"
use_latest_release = true
prefix = "v"

[gfold]
source = "github"
github = "nickgerace/gfold"
use_latest_release = true
prefix = "v"

[jilu]
source = "github"
github = "rustic-games/jilu"
use_latest_release = true
prefix = "v"

[hadlock]
source = "github"
github = "AdaShoelace/hadlock"
use_latest_release = true
prefix = "v"

[mmwm]
source = "github"
github = "kaugm/mmwm"

[frankenwm]
source = "github"
github = "sulami/FrankenWM"
use_max_tag = true
prefix = "v"

[conserve]
source = "github"
github = "sourcefrog/conserve"
use_latest_release = true
prefix = "v"

[stegano]
source = "github"
github = "steganogram/stegano-rs"
use_max_tag = true
prefix = "v"

[stegify]
source = "github"
github = "DimitarPetrov/stegify"
use_latest_release = true
prefix = "v"

[kbtui]
source = "github"
github = "Rudi9719/kbtui"
use_latest_release = true
prefix = "v"

[lipl]
source = "github"
github = "yxdunc/lipl"
use_latest_release = true
prefix = "v"

[kbs2]
source = "github"
github = "woodruffw/kbs2"
use_latest_release = true
prefix = "v"

[suckit]
source = "github"
github = "Skallwar/suckit"
use_latest_release = true
prefix = "v"

[funkicrab]
source = "github"
github = "zesterer/funkicrab"

[fhc]
source = "github"
github = "Edu4rdSHL/fhc"
use_latest_release = true
prefix = "v"

[eva]
source = "github"
github = "NerdyPepper/eva"
use_latest_release = true
prefix = "v"

[rusolver]
source = "github"
github = "Edu4rdSHL/rusolver"
use_latest_release = true
prefix = "v"

[unimap]
source = "github"
github = "Edu4rdSHL/unimap"
use_latest_release = true
prefix = "v"

[lfs]
source = "github"
github = "Canop/lfs"
use_latest_release = true
prefix = "v"

[rusty-krab-manager]
source = "github"
github = "aryakaul/rusty-krab-manager"
use_latest_release = true
prefix = "v"

[huniq]
source = "github"
github = "koraa/huniq"

[slicer]
source = "github"
github = "mzfr/slicer"
use_latest_release = true
prefix = "v"

[pwninit]
source = "github"
github = "io12/pwninit"
use_latest_release = true
prefix = "v"

[typeracer]
source = "gitlab"
gitlab = "ttyperacer/terminal-typeracer"
use_max_tag = true
prefix = "v"

[termimage]
source = "github"
github = "nabijaczleweli/termimage"
use_latest_release = true
prefix = "v"

[imgcat]
source = "github"
github = "trashhalo/imgcat"
use_latest_release = true
prefix = "v"

[muffet]
source = "github"
github = "raviqqe/muffet"
use_latest_release = true
prefix = "v"

[termchat]
source = "github"
github = "lemunozm/termchat"
use_latest_release = true
prefix = "v"

[fw]
source = "github"
github = "brocode/fw"
use_latest_release = true
prefix = "v"

[fblog]
source = "github"
github = "brocode/fblog"
use_latest_release = true
prefix = "v"

[goat]
source = "github"
github = "brocode/goat"
use_latest_release = true
prefix = "v"

[sic-image-cli]
source = "github"
github = "foresterre/sic"
use_latest_release = true
prefix = "v"

[globe]
source = "github"
github = "adamsky/globe"
use_max_tag = true
prefix = "v"

[cicero]
source = "github"
github = "eyeplum/cicero-tui"
use_latest_release = true
prefix = "v"

[verco]
source = "github"
github = "matheuslessarodrigues/verco"
use_latest_release = true
prefix = "v"

[color_blinder]
source = "gitlab"
gitlab = "dns2utf8/color_blinder"
use_max_tag = true
prefix = "v"

[bookmark]
source = "github"
github = "Szymongib/bookmark"
use_latest_release = true
prefix = "v"

[emptty]
source = "github"
github = "tvrzna/emptty"
use_latest_release = true
prefix = "v"

[fclones]
source = "github"
github = "pkolaczk/fclones"
use_latest_release = true
prefix = "v"

[dotter]
source = "github"
github = "SuperCuber/dotter"
use_latest_release = true
prefix = "v"

[ctree]
source = "github"
github = "Matt-Gleich/ctree"
use_latest_release = true
prefix = "v"

[prs]
source = "gitlab"
gitlab = "timvisee/prs"
use_max_tag = true
prefix = "v"

[tickrs]
source = "github"
github = "tarkah/tickrs"
use_latest_release = true
prefix = "v"

[t-rec]
source = "github"
github = "sassman/t-rec-rs"
use_latest_release = true
prefix = "v"
